service: nest-serverless-lambda-demo

provider:
 name: aws
 runtime: nodejs12.x
 region: 'us-west-2'

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'